### ISSUE TITLE
review current progress

### ISSUE THREAD

**Issue by williamsgareth** [GarethW1994/greetings#1]
@avermeulen @Onwa2014 @Oyamasiphula

**Comment by avermeulen** [comment]
Be consistent with your function names. Either use camelCare or under_scores. Don't mix things.

There are some `console.log` statements floating around - remove them.  @GarethW1994

**Comment by avermeulen** [comment]
@GarethW1994 move your smaller functions that are doing the same thing into one js file with an appropriate name.

**Comment by avermeulen** [comment]
@GarethW1994 use the `find` Array function for the `greetedBefore` function - move functions for greetings into one file.

**Comment by williamsgareth** [comment]
@avermeulen made some changes. Please review. Thank you.

**Comment by avermeulen** [comment]
@GarethW1994 what is the difference between the createMessage and generateMessage files? They seem to be the same. Remove the appropriate one. Remove unnecessary spaces.

**Comment by avermeulen** [comment]
@GarethW1994 rename `mainFunction.js` to `main.js` thats a better convention.

**Comment by williamsgareth** [comment]
@avermeulen okay I made the required changes.
